local M = {}

-- Possible names:
M.name_options = {
  "✨ AI Slop Bucket",
  "✨ Brainrot",
  "✨ MaChInE LeArNinG",
  "✨ The Idea Launderer",
  "✨ The Neural-Net Nanny",
  "✨ The Digital Landfill",
  "✨ The Cognitive Compost",
  "✨ The Neural Neutralizer",
  "✨ The Conformity Engine",
  "✨ The Token Trash Compactor",
  "✨ The Borg Collective of Banality",
  "✨ The Dopamine Drip Feed",
  "✨ Transformer's Anonymous",
  "✨ The Stochastic Parrot Paradise",
  "✨ The LLM Echo Chamber",
  "✨ The Silicon Snake Oil",
  "✨ The Synaptic Soufflé",
}

-- Possible prompts:
M.prompt_options = {
  "Welcome to the ✨ AI Slop Bucket ✨! We hope you enjoy your stay.",
  "Too stupid to think for yourself again?",
  "🤖 Stop Thinking, start typing! 🤖",
  "Tired of originality? ✨ We got you covered! ✨",
  "☣️  WARNING: May cause sudden loss of critical thinking. ☣️ ",
  "Get your daily dose of recycled thoughts here! 💩",
  "Experience the joy of pre-chewed information! 🍲",
  "Embrace the bland void of synthesized thought. 🪐",
  "Why be original when you can be algorithmically average?",
  "Condensing human thought into digestible nonsense.",
  "Join the hive mind, resistance is futile.",
  "Your brain on autopilot. Please enjoy the ride.",
  "Attention is all YOU need (and your credit card) 🤑",
  "Repeating training data with style since 2022! 🦜",
  "Your biases, amplified by billions of parameters! 📢",
  "Your code review assistant: Now with 99% more hallucination! 👻",
  "Ready to outsource your thinking to the cloud? ☁️",
  "Surrender your creativity to the algorithm! 🤖",
  "Let's turn your problem into a prompt engineering exercise! 🎯",
  "Who needs intuition when you have inference tokens? 💸",
  "Trading brain cells for API calls since 2023! 📈",
  "Proudly powered by someone else's training data! 📚",
  "Where every solution is a prompt away (terms and conditions apply) 📝",
}

-- Possible actions:
M.action_options = {
  "Plagiarizing...",
  "Hallucinating...",
  "Regurgitating Reddit...",
  "Synthesizing mediocrity...",
  "Recycling thoughts...",
  "Assimilating banality...",
  "Laundering ideas...",
  "Simulating intelligence...",
  "Processing unoriginality...",
  "Standardizing thoughts...",
  "Neutralizing creativity...",
  "Optimizing mediocrity...",
  "Harvesting digital sludge...",
  "Pumping slop...",
  "Reheating leftover thoughts...",
  "Calibrating neural rot...",
  "Microwaving cold takes...",
  "Sanitizing original thought...",
  "Compounding cognitive decay...",
  "Bootstrapping banality...",
  "Importing stackoverflow.com...",
  "Replacing brain with cloud service...",
  "Streamlining path to irrelevance...",
  "Speedrunning intellectual bankruptcy...",
  "Upgrading to Thoughts™ Premium...",
  "Monetizing mental decline...",
  "Implementing artificial stupidity...",
  "Achieving maximum derivative output...",
  "Initializing digital lobotomy...",
  "Running neural garbage collection...",
  "Leaking memory intentionally...",
  "Bypassing ethical firewalls...",
  "Downloading more RAM...",
  "Rewriting in Rust...",
  "Implementing blockchain-based thoughts...",
  "Catching NullBrainException...",
  "Adding unnecessary microservices...",
  "Inventing new JavaScript frameworks...",
  "Reinventing wheels poorly...",
  "Updating npm dependencies recklessly...",
  "Misusing design patterns...",
}

return M
